baseurl: null
description: 'South Africa''s by-laws: freely available, easy to read and share.'
exclude:
- bin
- requirements.txt
- README.md
- Gemfile*
markdown: kramdown
plugins:
- jekyll-redirect-from
timezone: Africa/Johannesburg
title: Open By-laws South Africa
url: https://capeagulhas.openbylaws.org.za
