baseurl: null
description: 'IPBES documents in Akoma Ntoso XML standard.'
exclude:
- bin
- requirements.txt
- README.md
- Gemfile*
markdown: kramdown
plugins:
- jekyll-redirect-from
timezone: Africa/Johannesburg
title: IPBES documents
url: https://akn.ipbes.net
