---
title: Open By-laws South Africa
timezone: Africa/Johannesburg
description: "South Africa's by-laws: freely available, easy to read and share."
baseurl: 
url: https://openbylaws.org.za
markdown: kramdown
plugins:
- jekyll-redirect-from
exclude:
- bin
- requirements.txt
- README.md
- Gemfile*
